### ISSUE TITLE
Schema 'schema.json' is not valid: /properties/type : must be object,boolean YAML(768)

### ISSUE THREAD

**Issue by Paul-16098** [not-first/glance-schema#1]
![Image](https://github.com/user-attachments/assets/bc5dce49-090c-4a8e-8960-49645180c31b)

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/not-first/glance-schema/master/schema.json

server:
  assets-path: ./assets
```
Visual Studio Code
版本: 1.100.3 (system setup)
認可: 258e40fedc6cb8edf399a463ce3a9d32e7e1f6f3
日期: 2025-06-02T13:30:54.273Z
Electron: 34.5.1
ElectronBuildId: 11369351
Chromium: 132.0.6834.210
Node.js: 20.19.0
V8: 13.2.152.41-electron.0
OS: Windows_NT x64 10.0.26100

名稱: YAML
識別碼: redhat.vscode-yaml
描述: YAML Language Support by Red Hat, with built-in Kubernetes syntax support
版本: 1.18.0
發行者: Red Hat
